### ISSUE TITLE
tomighty-windows-1.0.0.0-beta04 can't run on win7.

### ISSUE THREAD

**Issue by easior** [tomighty/tomighty-windows#9]
I installed tomighty on win 7 by using tomighty-windows-1.0.0.0-beta04-install.exe. But it can't run and always reports : 

> System.TypeLoadException: Could not find Windows Runtime type 'Windows.UI.Notifications.ToastNotificationManager'. ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
>    --- End of inner exception stack trace ---
>    at Tomighty.Windows.Notifications.NotificationsPresenter..ctor(IPomodoroEngine pomodoroEngine, IUserPreferences userPreferences, IEventHub eventHub)
>    at Tomighty.Windows.TomightyApplication..ctor()
>    at Tomighty.Windows.Program.Main()

Please fix it.

**Comment by deividfortuna** [comment]
Same problem here!
